apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-api-weatherapi-com
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 443
        name: https-api-weatherapi-com-443
        protocol: TLS # Mark as TLS as we are passing HTTPS through.
      hosts:
        - weatherapi.com
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-api-weatherapi-com
spec:
  hosts:
    - api.weatherapi.com
  gateways:
    - https-api-weatherapi-com
  tls:
    - match:
        - ports: 443
          sniHosts:
            - weatherapi.com
      route:
        - destination:
            host: egress-api-weatherapi-com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-https-api-weatherapi-com
spec:
  hosts:
    - egress-api-weatherapi-com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: weatherapi.com
    ports:
      http: 443