#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: weatherapi-se
#spec:
#  hosts:
#    - api.weatherapi.com
#  ports:
#    - number: 80
#      name: http
#      protocol: HTTP
#      targetPort: 443
#    - number: 443
#      name: https
#      protocol: HTTPS
#  resolution: DNS
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: weatherapi-dest-rule
#spec:
#  host: api.weatherapi.com
#  trafficPolicy:
#    portLevelSettings:
#      - port:
#          number: 80
#        tls:
#          mode: SIMPLE # initiates HTTPS when accessing api.weatherapi.com
#

####### Above version is simple TLS origination #######################
####### An intermediate solution to test GW ################
#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
  #name: weather-se
#spec:
  #hosts:
    #- api.weatherapi.com
  #ports:
    #- number: 80
      #name: http-port
      #protocol: HTTP
    #- number: 443
      #name: https
      #protocol: HTTPS
  #resolution: DNS
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
  #name: egress-gw
#spec:
  #selector:
    #istio: egressgateway
  #servers:
    #- port:
        #number: 80
        #name: http
        #protocol: HTTP
      #hosts:
        #- api.weatherapi.com
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
  #name: egress-dr
#spec:
  #host: egress-gw.weather.svc.cluster.local
  #subsets:
    #- name: weather-se
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
  #name: weather-vs
#spec:
  #hosts:
    #- api.weatherapi.com
  #gateways:
    #- egress-gw
  #http:
    #- match:
        #- gateways:
            #- egress-gw
          #port: 80
      #route:
        #- destination:
            #host: api.weatherapi.com
            #port:
              #number: 80
          #weight: 100


####### Below we try to create TLS origination with Egress GW #########
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: weatherapi-se
spec:
  hosts:
    - api.weatherapi.com
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-api
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-api-dr
spec:
  host: egress-api
  subsets:
  - name: api

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-api-through-gw
spec:
  hosts:
    - api.weatherapi.com
  gateways:
    - egress-api
    - mesh
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: egress-api
            subset: api
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - egress-api
          port: 80
      route:
        - destination:
            host: api.weatherapi.com
            port:
              number: 80
          weight: 100

#---
#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: weatherapi-local-se
#spec:
#  hosts:
#    - api.weatherapi.local
#  ports:
#    - number: 80
#      name: http
#      protocol: HTTP
#    - number: 443
#      name: https
#      protocol: HTTPS
#  resolution: NONE
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: egress-gw
#spec:
#  selector:
#    istio: egressgateway
#  servers:
#    - port:
#        number: 80
#        name: https-port
#        protocol: HTTPS
#      hosts:
#        - api.weatherapi.com
#      tls:
#        mode: ISTIO_MUTUAL
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: egress-dr
#spec:
#  host: egress-gw.weather.svc.cluster.local
#  subsets:
#    - name: egress-se
#      trafficPolicy:
#        loadBalancer:
#          simple: ROUND_ROBIN
#        portLevelSettings:
#        - port:
#            number: 80
#          tls:
#            mode: ISTIO_MUTUAL
#            sni: api.weatherapi.com
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: egress-vs
#spec:
#  hosts:
#    - api.weatherapi.local
#  gateways:
#    - egress-gw
#    - mesh
#  http:
#    - match:
#        - gateways:
#            - egress-gw
#            - mesh
#          port: 80
#      redirect:
#        authority: api.weatherapi.com
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: originate-dr
#spec:
#  host: api.weatherapi.com
#  trafficPolicy:
#    loadBalancer:
#      simple: ROUND_ROBIN
#    portLevelSettings:
#      - port:
#          number: 443
#        tls:
#          mode: SIMPLE # initiates HTTPS