apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: weatherapi-se
spec:
  hosts:
    - api.weatherapi.com
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: weather-egress-gw
#spec:
#  selector:
#    istio: egressgateway
#  servers:
#    - port:
#        number: 80
#        name: https-port-for-tls-origination
#        protocol: HTTPS
#      hosts:
#        - api.weatherapi.com
#      tls:
#        mode: ISTIO_MUTUAL
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: weather-egress-gw
#spec:
#  host: weather-egress-gw.istio-system.svc.cluster.local
#  subsets:
#    - name: weatherapi-se
#      trafficPolicy:
#        loadBalancer:
#          simple: ROUND_ROBIN
#        portLevelSettings:
#          - port:
#              number: 80
#            tls:
#              mode: ISTIO_MUTUAL
#              sni: api.weatherapi.com