#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: weatherapi-se
#spec:
#  hosts:
#    - api.weatherapi.com
#  ports:
#    - number: 80
#      name: http
#      protocol: HTTP
#      targetPort: 443
#    - number: 443
#      name: https
#      protocol: HTTPS
#  resolution: DNS
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: weatherapi-dest-rule
#spec:
#  host: api.weatherapi.com
#  trafficPolicy:
#    portLevelSettings:
#      - port:
#          number: 80
#        tls:
#          mode: SIMPLE # initiates HTTPS when accessing api.weatherapi.com
#

####### Above version is simple TLS origination #######################

####### Below we try to create TLS origination with Egress GW #########
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-se
spec:
  hosts:
    - api.weatherapi.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-gw
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - api.weatherapi.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-dr
spec:
  host: egress-gw.weather.svc.cluster.local
  subsets:
    - name: egress-se
