#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: weatherapi-local-se
#  namespace: weather
#spec:
#  hosts:
#    - weatherapi.internal
#  ports:
#    - number: 80
#      name: http
#      protocol: HTTP
#    - number: 443
#      name: https
#      protocol: HTTPS
#  addresses:
#    - 192.168.100.100
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: egress-vs
#spec:
#  hosts:
#    - weatherapi.internal
#  gateways:
#    - egress-gw
#    - mesh
#  http:
#    - match:
#        - gateways:
#            - egress-gw
#          port: 80
#      rewrite:
#        authority: api.weatherapi.com
#      route:
#        - destination:
#            host: api.weatherapi.com
#            port:
#              number: 443
#    - match:
#        - gateways:
#            - mesh
#          port: 80
#      route:
#        - destination:
#            host: egress-gw.weather.svc.cluster.local
#            port:
#              number: 80
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: egress-gw
#spec:
#  selector:
#    istio: egressgateway
#  servers:
#    - port:
#        number: 80
#        name: https-port
#        protocol: HTTPS
#      hosts:
#        - "*"
#      tls:
#        mode: ISTIO_MUTUAL
#---