apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: weatherapi-se
spec:
  hosts:
    - api.weatherapi.com
  ports:
    - number: 443
      name: http
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL