apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: weatherapi-local-se
  namespace: weather
spec:
  hosts:
    - weatherapi.internal
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  addresses:
    - 192.168.100.100