apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: weatherapi
spec:
  hosts:
    - api.weatherapi.com
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: weather-egressgw
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - api.weatherapi.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: weather-egressgw
spec:
  host: weather-egressgw.istio-system.svc.cluster.local
  subsets:
    - name: weatherapi
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weather-vservice
spec:
  hosts:
    - api.weatherapi.com
  gateways:
    - weather-egressgw
    - mesh
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: weather-egressgw.istio-system.svc.cluster.local
            subset: weatherapi
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - weather-egressgw
          port: 80
      route:
        - destination:
            host: api.weatherapi.com
            port:
              number: 80
          weight: 100